name:                bot
version:             0.1.0.0
github:              "wmean/bot"
license:             BSD3
author:              "Evgeniy Rybin"
maintainer:          "z.ribin20@gmail.com"
copyright:           "2022 Evgeniy Rybin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wmean/bot#readme>

dependencies:
- base >= 4.7 && < 5
- HTTP
- http-types
- http-client
- http-client-tls
- mtl
- exceptions
- bytestring

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
